# For more info on HTTP files go to https://aka.ms/vs/httpfile

@daprPort = 64460
@appId = apiservice
@workflowId = OrderProcessingWorkflow
@instanceId = d022c94f

### Start Workflow
POST http://localhost:{{daprPort}}/v1.0/workflows/{{appId}}/{{workflowId}}/start?instanceID={{instanceId}}
dapr-app-id: {{appId}}


### Get Status
GET http://localhost:{{daprPort}}/v1.0/workflows/{{appId}}/{{instanceId}}
dapr-app-id: {{appId}}


### Purge Workflow
POST http://localhost:{{daprPort}}/v1.0/workflows/{{appId}}/{{instanceId}}/purge
dapr-app-id: {{appId}}