apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: development
spec:
  type: secretstores.local.file
  version: v1
  initTimeout: 60s
  metadata:
  - name: secretsFile
    value: ..\.dapr\store\secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"