#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: redis-config-store
#  namespace: development
#spec:
#  type: configuration.redis
#  initTimeout: 60s
#  metadata:
#  - name: redisHost
#    value: localhost:6379
#  - name: redisPassword
#    value: ""