apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqlserver-state-store
spec:
  type: state.sqlserver
  version: v1
  initTimeout: 60s
  metadata:
    - name: connectionString
      secretKeyRef:
        name: ConnectionStrings:StateManagement
    - name: tableName
      value: SystemState
    - name: metadataTableName
      value: SystemStateMetadata
    - name: schema
      value: framework_core
    - name: keyType
      value: string
    - name: keyLength
      value: 200
    - name: keyPrefix
      value: none
    - name: cleanupIntervalInSeconds
      value: 3600
    - name: actorStateStore
      value: true
auth:
  secretStore: local-secret-store